config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'pages/programliftoff'
  get 'pages/webdesign'
  get 'pages/services'
  get 'pages/culture'
  get 'pages/shop'
  get 'pages/spaceship'
  get 'pages/projects'
  get 'storeapp/index'
  get 'app/index'

  root 'pages#home'

  resources :projects
  resources :currentupdates

  resources :posts, only: [:create, :index, :show] do
    resources :comments, only: [:show, :create] do
      member do
        put '/upvote' => 'comments#upvote'
      end
    end

    member do
      put 'upvote' => 'posts#upvote'
    end
  end
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  	def as_json(options = {})
		super(options.merge(include: :user))
	end
end

app/models/currentupdate.rb
class Currentupdate < ActiveRecord::Base
	
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	belongs_to :user

	def as_json(options = {})
		super(options.merge(include: [:user, comments: {include: :user}]))
	end
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_attached_file :image, :styles => {:large => "600x600>", :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	default_scope -> { order(ordernumber: :asc) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/app_controller.rb
class AppController < ApplicationController
	layout "app"
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  respond_to :json

   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!, only: [:create, :upvote]

	def create
		post = Post.find(params[:post_id])
		comment = post.comments.create(comment_params.merge(user_id: current_user.id))
		respond_with post, comment
	end

	def upvote
		post = Post.find(params[:post_id])
		comment = post.comments.find(params[:id])
		comment.increment!(:upvotes)

		respond_with post, comment
	end

	private
	def comment_params
		params.require(:comment).permit(:body)
	end
end	

app/controllers/currentupdates_controller.rb
class CurrentupdatesController < ApplicationController
	before_action :set_currentupdate, only: [:edit, :update, :destroy]


  def new
    @currentupdate = Currentupdate.new
  end

  def create

    @currentupdate = Currentupdate.new(currentupdate_params)

    if @currentupdate.save
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    if @currentupdate.update(currentupdate_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @currentupdate.destroy
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_currentupdate
      @currentupdate = Currentupdate.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def currentupdate_params
      params.require(:currentupdate).permit(:info)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@projects = Project.all
  	@currentupdate = Currentupdate.last
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	  before_filter :authenticate_user!, only: [:create, :upvote]

	def index
		respond_with Post.all
	end

	def create
		respond_with Post.create(post_params.merge(user_id: current_user.id))
	end

	def show
		respond_with Post.find(params[:id])
	end

	def upvote
		post = Post.find(params[:id])
		post.increment!(:upvotes)

		respond_with post
	end

	private
	def post_params
		params.require(:post).permit(:link, :title)
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create

    @project = Project.new(project_params)

    if @project.save
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    if @project.update(project_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:image, :title, :description, :info, :ordernumber, :link)
    end
end

app/controllers/storeapp_controller.rb
class StoreappController < ApplicationController
	layout "storeapp"
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/currentupdates_helper.rb
module CurrentupdatesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/currentupdates/_form.html.erb
<div class="panel-heading">
    <h1>Add Update</h1>
  </div>

<div class="panel-body">
  <div class="panel panel-default">
    <%= form_for @currentupdate, html: { multipart: true } do |f| %>
      <% if @currentupdate.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@currentupdate.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
          <% @currentupdate.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :info %>
        <%= f.text_field :info, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/currentupdates/edit.html.erb
<div class="signup-back">
	<%= render 'form' %>
</div>

app/views/currentupdates/new.html.erb
<div class="signup-back">
	<%= render 'form' %>
</div>

app/views/layouts/_header.html.erb
<nav class="topbar">
      <%= link_to root_path do %>
            <div class="titleheader">

                <%= image_tag 'itsaspaceship.png', :class => "logo-head2" %>
            </div>
      <% end %>

      <ul>
        <li><%= link_to root_path do %><i class="fa fa-rocket"></i><% end %></li>
        <li><%= link_to pages_webdesign_path do %><i class="fa fa-ship"></i><% end %></li>
        <li><%= link_to pages_culture_path do %><i class="fa fa-subway"></i><% end %></li>
        <li><%= link_to pages_shop_path do %><i class="fa fa-truck"></i><% end %></li>
      </ul>

</nav>

<div id="menu-icon">
    <i class="fa fa-bomb"></i>
</div>

<div class="overlay nodisplay"></div>

<div class="rightmenu">
  <ul>
    <li>
      <%= link_to root_path do %>
      <%= image_tag 'itsaspaceship-blue.png', :class => "logo-menu" %>
      <% end %>

    </li>
    <li>cc@ccevans.com</li>
    <li>

    <a class="typeform-share link" href="https://starttoday.typeform.com/to/qkyqZx" data-mode="2" target="_blank">Start Launch</a>
    <script>(function(){var qs,js,q,s,d=document,gi=d.getElementById,ce=d.createElement,gt=d.getElementsByTagName,id='typef_orm',b='https://s3-eu-west-1.amazonaws.com/share.typeform.com/';if(!gi.call(d,id)){js=ce.call(d,'script');js.id=id;js.src=b+'share.js';q=gt.call(d,'script')[0];q.parentNode.insertBefore(js,q)}})()</script>

    </li>
    <li>

      <a class="typeform-share link" href="https://starttoday.typeform.com/to/FZpsEl" data-mode="2" target="_blank">Schedule Call</a>
      <script>(function(){var qs,js,q,s,d=document,gi=d.getElementById,ce=d.createElement,gt=d.getElementsByTagName,id='typef_orm',b='https://s3-eu-west-1.amazonaws.com/share.typeform.com/';if(!gi.call(d,id)){js=ce.call(d,'script');js.id=id;js.src=b+'share.js';q=gt.call(d,'script')[0];q.parentNode.insertBefore(js,q)}})()</script>


    </li>

    <li>
      <%= link_to root_path do %>
      <i class="fa fa-rocket fa-fw"></i><span class="menu-li">Projects</span>
      <% end %>

    </li>
    <li>
      <%= link_to pages_webdesign_path do %>
      <i class="fa fa-ship fa-fw"></i><span class="menu-li">Services</span>
      <% end %>

    </li>
    <li>
      <%= link_to pages_culture_path do %>
      <i class="fa fa-subway fa-fw"></i><span class="menu-li">Culture & Events</span>
      <% end %>

    </li>
      <li>
      <%= link_to pages_shop_path do %>
      <i class="fa fa-truck fa-fw"></i><span class="menu-li">Shop Incubator</span>
      <% end %>

    </li>

    <li>
      <%= link_to "http://weloveclt.com/", :target => "_blank" do %>
      <%= image_tag 'footer-icon.png', :class => "" %>
      <% end %>

    </li>
  </ul>



  </div>


<script>
  $('#menu-icon').click(function(){
    $('.rightmenu').addClass('revealed');
    $('.overlay').removeClass('nodisplay');
    $('body').addClass("noscroll");
  });
  $('.overlay').click(function(){
    $('.rightmenu').removeClass('revealed');
    $('.overlay').addClass('nodisplay');
    $('body').removeClass("noscroll");
  });
</script>

app/views/layouts/_header2.html.erb
<nav class="topbar">
      <%= link_to root_path do %>
            <div class="titleheader">

                <%= image_tag 'itsaspaceship.png', :class => "logo-head2" %>
            </div>
      <% end %>

</nav>

<div id="menu-icon">
    <i class="fa fa-bomb"></i>
</div>

<div class="overlay nodisplay"></div>

<div class="rightmenu">
  <ul>
    <li>
      <%= link_to root_path do %>
      <%= image_tag 'itsaspaceship-blue.png', :class => "logo-menu" %>
      <% end %>

    </li>
    <li>CC Evans</li>
    <li>cc@ccevans.com</li>

    <li>

    </li>
  </ul>



  </div>


<script>
  $('#menu-icon').click(function(){
    $('.rightmenu').addClass('revealed');
    $('.overlay').removeClass('nodisplay');
    $('body').addClass("noscroll");
  });
  $('.overlay').click(function(){
    $('.rightmenu').removeClass('revealed');
    $('.overlay').addClass('nodisplay');
    $('body').removeClass("noscroll");
  });
</script>

app/views/layouts/app.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flapper News</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>



     <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" media="all" rel="stylesheet" type="text/css" />

  <meta name="viewport" content="width=device-width" />

  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-70989632-2', 'auto');
  ga('send', 'pageview');

</script>

  <script src="//use.typekit.net/pxh4euk.js"></script>
<script>try{Typekit.load();}catch(e){}</script>


</head>
<body ng-app="flapperNews" >




<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ccevans.com</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

 

     <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" media="all" rel="stylesheet" type="text/css" />

     <link href='https://fonts.googleapis.com/css?family=VT323' rel='stylesheet' type='text/css'>

  <meta name="viewport" content="width=device-width" />

  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-70989632-2', 'auto');
  ga('send', 'pageview');

</script>

  <script src="//use.typekit.net/pxh4euk.js"></script>
<script>try{Typekit.load();}catch(e){}</script>


</head>
<body>

<% if current_page?(root_path) %>
    <%= render 'layouts/header2' %>

<% else %>

    <%= render 'layouts/header' %>
<% end %>

<%= yield %>

</body>
</html>

app/views/pages/culture.html.erb
<section class="culture-section">

<h1>Culture and Events Coming Soon.</h1>

</section>

app/views/pages/projects.html.erb
<section class="liftoff-projects">

  <div class="projectheader">
    <span class="projectcount">12</span><span class="projecttitle">projects<br>launched</span><br>

    <div class="launchtoday">

    <a class="typeform-share link" href="https://starttoday.typeform.com/to/qkyqZx" data-mode="2" target="_blank">Launch Your Project Today</a>  
    <script>(function(){var qs,js,q,s,d=document,gi=d.getElementById,ce=d.createElement,gt=d.getElementsByTagName,id='typef_orm',b='https://s3-eu-west-1.amazonaws.com/share.typeform.com/';if(!gi.call(d,id)){js=ce.call(d,'script');js.id=id;js.src=b+'share.js';q=gt.call(d,'script')[0];q.parentNode.insertBefore(js,q)}})()</script>

    <br><%= link_to pages_webdesign_path do %>Learn More<% end %>
    </div>

   

  </div>

  <div class="programliftoff nodisplay">
    <h1>Program Liftoff</h1>

    <p>We specialized in launching new ideas and businesses.  While building our own projects, we also offer to help other creatives and entrepreneurs.  Program liftoff allows you to get a professional web presence in weeks.  Program liftoff provides everything an entrepreneur or creative will need to advance their venture online and allow them to focus on what they love.  We excel at creating unique ideas and concepts.  If you need custom and advanced work, we can help get your project off the ground.  We provide web services ranging from websites, web apps and full ecommerce websites.  Get a quote in 48 hours.</p>

        <a class="typeform-share link" href="https://starttoday.typeform.com/to/qkyqZx" data-mode="2" target="_blank">Launch Your Project Today</a>
    <script>(function(){var qs,js,q,s,d=document,gi=d.getElementById,ce=d.createElement,gt=d.getElementsByTagName,id='typef_orm',b='https://s3-eu-west-1.amazonaws.com/share.typeform.com/';if(!gi.call(d,id)){js=ce.call(d,'script');js.id=id;js.src=b+'share.js';q=gt.call(d,'script')[0];q.parentNode.insertBefore(js,q)}})()</script>


  </div>

	<%= image_tag 'ishdone.png', :class => "spaceshipsite-image2" %>

	<%= link_to "http://www.plugsapp.com", :target => "_blank" do %>
	<%= image_tag 'spaceship-plugs-site.png', :class => "spaceshipsite-image" %>
	<% end %>

	<%= link_to "http://www.dailylyric.com", :target => "_blank" do %>
	<%= image_tag 'spaceship-dailylyric-site.png', :class => "spaceshipsite-image" %>
	<% end %>

	<%= link_to "http://www.rhymesanddesigns.com", :target => "_blank" do %>
	<%= image_tag 'spaceship-rnd-site.png', :class => "spaceshipsite-image" %>
	<% end %>

	<div class="spaceship-box">
    <h1>Our Mission</h1>
		<p>it's a spaceship is platform to launch different ideas and concepts.  It is a incubator and accelerator of tech businesses, cool ideas and cultural projects. We love launching new and exciting ideas, so each month or two we will be launching new concepts of our own to test in the market. Each idea will be either turn into a lifestyle business, passive income, killed off, given to a team to manage or hopefully into a high growth startup.  Our overall goal is to create a platform right here in Charlotte to launch creative, tech and cultural concepts.</p>

		<p>With that being said, we are looking for individuals who are want to learn how to build apps, websites and businesses and can bring something to the table. This will be a great opportunity to be a part of something with potential to grow.  I'm looking to build a diverse team of different backgrounds and perspectives.  Also looking for investors and partners to help with resources as the team and ideas expand.</p>

		<p>While building cool concepts for ourselves, we also provide web design services for others. <%= link_to "Checkout our portfolio", pages_webdesign_path %> and learn how we can build something unique for your brand. We are also partners with an interactive agency, <%= link_to "330 Monday", "http://www.330monday.com" %>, where we can help with marketing and engaging with your target market.</p>

		<p>My team and I love doing cultural projects and expanding the community.  We provide more details on the cool projects we got coming up soon.  Make sure to sign up if you are interested in seeing what we come up with and helping out the process with feedback.</p>

		<p>CC Evans</p>

	</div>

<div class="spaceship-signup">
		<style>
  .gumroad-follow-form-embed {
    zoom: 1; }
    .gumroad-follow-form-embed:before, .gumroad-follow-form-embed:after {
      display: table;
      line-height: 0;
      content: ""; }
    .gumroad-follow-form-embed:after {
      clear: both; }
    .gumroad-follow-form-embed * {
      margin: 0;
      border: 0;
      padding: 0;
      outline: 0;
      box-sizing: border-box !important;
      float: left !important; }
    .gumroad-follow-form-embed input {
      border-radius: 4px;
      border-top-right-radius: 0;
      border-bottom-right-radius: 0;
      font-family: -apple-system, ".SFNSDisplay-Regular", "Helvetica Neue", Helvetica, Arial, sans-serif;
      font-size: 15px;
      line-height: 20px;
      background: #fff;
      border: 1px solid #ddd;
      border-right: 0;
      color: #aaa;
      padding: 10px;
      box-shadow: inset 0 1px 0 rgba(0, 0, 0, 0.02);
      background-position: top right;
      background-repeat: no-repeat;
      text-rendering: optimizeLegibility;
      font-smoothing: antialiased;
      -webkit-appearance: none;
      -moz-appearance: caret;
      width: 65% !important;
      height: 40px !important; }
    .gumroad-follow-form-embed button {
      border-radius: 4px;
      border-top-left-radius: 0;
      border-bottom-left-radius: 0;
      box-shadow: 0 1px 1px rgba(0, 0, 0, 0.12);
      -webkit-transition: all .05s ease-in-out;
      transition: all .05s ease-in-out;
      display: inline-block;
      padding: 11px 15px 12px;
      cursor: pointer;
      color: #fff;
      font-size: 15px;
      line-height: 100%;
      font-family: -apple-system, ".SFNSDisplay-Regular", "Helvetica Neue", Helvetica, Arial, sans-serif;
      background: #000;
      border: 1px solid #000;
      height: 40px !important;
      width: 35% !important; }
</style>
<form action="https://gumroad.com/follow_from_embed_form" class="form gumroad-follow-form-embed" method="post">
<input name="seller_id" value="2086268218845" type="hidden">
<input name="email" placeholder="Your email address" type="email">
<button type="submit">Subscribe</button>
</form>

</div>


</section>

<script>
  $('#learnclick').click(function(){
    $('.programliftoff').removeClass('nodisplay');
  });
</script>

app/views/pages/services.html.erb
<section class="liftoff-projects">

	<%= image_tag 'greatwork.png', :class => "spaceshipsite-image3" %>

	<%= link_to pages_webdesign_path do %>
	<%= image_tag 'spaceship-service-webdesign.png', :class => "spaceshipsite-image4" %>
	<% end %>

	<%= link_to "http://www.330monday.com" do %>
	<%= image_tag 'spaceship-service-330monday2.png', :class => "spaceshipsite-image6" %>
	<% end %>


</section>

<section class="block-hire-service">
		<div class="hire-box">
			<div class="hire-box2">
				<h1>Ready To Launch?</h1><div class="clear"></div>
				<h4>Available for freelance, contract work and business projects.</h4>
				<div class="clear"></div>

				<h2>Contact Me</h2>
				<ul>
					<li>Email at cc@ccevans.com</li>
					<li>Text at 704-458-3043</li>
					<li>    
				    <a class="typeform-share link" href="https://starttoday.typeform.com/to/qkyqZx" data-mode="2" target="_blank">Start Launch</a>
				    <script>(function(){var qs,js,q,s,d=document,gi=d.getElementById,ce=d.createElement,gt=d.getElementsByTagName,id='typef_orm',b='https://s3-eu-west-1.amazonaws.com/share.typeform.com/';if(!gi.call(d,id)){js=ce.call(d,'script');js.id=id;js.src=b+'share.js';q=gt.call(d,'script')[0];q.parentNode.insertBefore(js,q)}})()</script>
					</li>

				</ul>
			</div>

			<%= image_tag 'space-launch.png', :class => "block-image4" %>


		</div>

</section> 

app/views/pages/shop.html.erb
<section class="culture-section">

<h1>Merch and Shop Coming Soon.</h1>

</section>

app/views/pages/spaceship.html.erb
<section class="block-story">

		<%= image_tag 'itsaspaceship-blue.png', :class => "spaceship-image" %>

<div class="spaceship-signup">
		<style>
  .gumroad-follow-form-embed {
    zoom: 1; }
    .gumroad-follow-form-embed:before, .gumroad-follow-form-embed:after {
      display: table;
      line-height: 0;
      content: ""; }
    .gumroad-follow-form-embed:after {
      clear: both; }
    .gumroad-follow-form-embed * {
      margin: 0;
      border: 0;
      padding: 0;
      outline: 0;
      box-sizing: border-box !important;
      float: left !important; }
    .gumroad-follow-form-embed input {
      border-radius: 4px;
      border-top-right-radius: 0;
      border-bottom-right-radius: 0;
      font-family: -apple-system, ".SFNSDisplay-Regular", "Helvetica Neue", Helvetica, Arial, sans-serif;
      font-size: 15px;
      line-height: 20px;
      background: #fff;
      border: 1px solid #ddd;
      border-right: 0;
      color: #aaa;
      padding: 10px;
      box-shadow: inset 0 1px 0 rgba(0, 0, 0, 0.02);
      background-position: top right;
      background-repeat: no-repeat;
      text-rendering: optimizeLegibility;
      font-smoothing: antialiased;
      -webkit-appearance: none;
      -moz-appearance: caret;
      width: 65% !important;
      height: 40px !important; }
    .gumroad-follow-form-embed button {
      border-radius: 4px;
      border-top-left-radius: 0;
      border-bottom-left-radius: 0;
      box-shadow: 0 1px 1px rgba(0, 0, 0, 0.12);
      -webkit-transition: all .05s ease-in-out;
      transition: all .05s ease-in-out;
      display: inline-block;
      padding: 11px 15px 12px;
      cursor: pointer;
      color: #fff;
      font-size: 15px;
      line-height: 100%;
      font-family: -apple-system, ".SFNSDisplay-Regular", "Helvetica Neue", Helvetica, Arial, sans-serif;
      background: #e74d3c;
      border: 1px solid #d04536;
      filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr=#ff7362, endColorstr=#d64738, GradientType=0)";
      background: -webkit-linear-gradient(top, #ff7362, #d64738);
      background: linear-gradient(to bottom, #ff7362, #d64738);
      height: 40px !important;
      width: 35% !important; }
</style>
<form action="https://gumroad.com/follow_from_embed_form" class="form gumroad-follow-form-embed" method="post">
<input name="seller_id" value="2086268218845" type="hidden">
<input name="email" placeholder="Your email address" type="email">
<button type="submit">Subscribe</button>
</form>

</div>

	<div class="spaceship-box">
		<p>it's a spaceship is platform to launch different ideas and concepts.  It will start out as a platform to house all my ideas, businesses, and cultural projects, but I plan to expand it into an incubator and accelerator for people with cool ideas.  The first goal is to launch a new concept on an average of 30 days until I find something worth investing resources into.  Some concepts will take less than 30 days and others a little more.  Check out our first concept, <%= link_to "dailylyric.com", "http://www.dailylyric.com" %>. Most of these ideas will be tech based.  Right now I'm a team of one and hoping to grow the team over time.  Each idea will be either turn into a lifestyle business, passive income, killed off, given to a team to manage or hopefully into a high growth startup.  My overall goal is to create a platform right here in Charlotte to launch creative, tech and cultural concepts.  Right now I'm not going to put it in a box and develop the plan as I see fit.</p>

		<p>With that being said, I'm looking for creatives or whatever you want to call yourself.  I just need people looking to learn and do whatever needs to get done.  If you are looking to learn how to build apps, websites and businesses and can bring something to the table, this will be a great opportunity to be a part of something with potential to grow.  I'm looking to build a diverse team with a focus on finding minority talent.  Also looking for investors and partners to help with resources as the team and ideas expand.</p>

		<p>While working on these concepts, I will also be providing freelance services to help fund the platform.  <%= link_to "I offer web design and development work, if you looking for a dope site.", pages_webdesign_path %>  Also a partner in the interactive agency, <%= link_to "330 Monday", "http://www.330monday.com" %>, where my partners can help with marketing and engaging with your target market.  I also have a MBA and experience working for a multibillion dollar company and can help take your business to the next level in a partnership/freelance/consulting capacity.  Also a partner in <%= link_to "Rhymes & Designs", "http://www.rhymesanddesigns.com" %>, where my partner is building a team to expand that venture and I help with tech.</p>

		<p>Like I said, this platform will house my cultural projects also like the Spiked Punch events and community <%= link_to "Art Wall", "http://anartspace.herokuapp.com/" %>.  While building dope concepts, I hope to continue to build community and expand the culture.  Make sure to sign up if you are interested in seeing what we come up with and helping out the process with feedback.</p>

		<p>CC Evans</p>

	</div>
	
		<%= image_tag 'waiting-spaceship-black2.png', :class => "block-image1" %>

				<%= image_tag 'moon-black.png', :class => "block-image2" %>


</section>

app/views/projects/index.html.erb
    <% if @projects.any? %>

    <% @projects.each do |project| %>
    <ul>
    	<li><%= project.title %></li>
    	<li><%= project.description %></li>
    	<li><%= project.info %></li>
    	<li><%= project.link %></li>
    	<li><%= project.ordernumber %></li>
    	<li><%= link_to 'Edit', edit_project_path(project) %></li>
    	<li><%= link_to 'Destroy', project, method: :delete, data: {confirm: "Are you sure?" } %></li>
    </ul>
    <% end %>
    <% end %>